### ISSUE TITLE
Sound propagation should account for custom distance attenuation curves

### ISSUE THREAD

**Issue by lakulish** [ValveSoftware/steam-audio#11]
In the Unity plugin, the Audio Source can be configured to use a non-physical distance attenuation curve, and the Phonon Effect can be configured to use that curve. However, sound propagation simulation does not seem to be using the custom attenuation curve properly.

**Comment by WildCat-ZA** [comment]
Specifically, sound propagation effects (reverb/reflections) seem to be improperly attenuated. I suspect that the reverb/reflection system is using an audio stream from Unity that has been pre-attenuated based on the distance between the Listener and the Source. If you set Direct Mix Fraction to 0 (so that you only hear the reverbs/reflections), then the problem becomes more obvious. The reflections become substantially quieter when you move away from the Audio Source.

**Comment by AndersMalmgren** [comment]
Guys, we really want to use steam audio but the aggressive cutoff  both from distance and oclussion makes this plugin sadly pretty unusable, how close are you to release a version addressing this?

**Comment by achandak** [comment]
@AndersMalmgren - WIP. Unfortunately, do not have a ETA for you on this. We are still investigating the issue.

**Comment by matteumayo** [comment]
Any updates?

**Comment by Luux** [comment]
This is still a problem. When trying to use a custom curve, it seems to ignore the attenuation completely. Even if i set maximum distance to 2, I can still hear the sound all over the map with disabled physics based attenuation.

**Comment by Schroedingers-Cat** [comment]
This issue is now 1.5 years old. Any update?  
Did you come up with any workarounds? I'm thinking about programatically controlling the indirect reflections level, but didn't come up with an artist friendly concept. It would be best to have this as a curve in the AudioSource's 3D settings next to all the other parameters. Any ideas how to achieve that?

**Comment by Samdosoft** [comment]
Is this still WIP? Are there any news regarding custom attenuation curves for indirect sounds? Thanks!

**Comment by mojoyup1528** [comment]
I would like to know this as well. My issue is a complete drop in acoustics when a source and receiver are not visibly seen by each other, so zero zero zero diffraction etc. I NEEED this for a program I have been working on for months. Otherwise, trashcan it goes :/ Raycasting and distance attenuation should be not so tough to impliment. The problem with raycasting at the moment is that the plugin does not repeat ray reflections, I believe. I am sure it only casts a single ray and then thats about it......Not really tru raycasting quite yet, which is essential to solving these diffraction issues.

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), includes this feature.

Refer to the documentation for more details. Feel free to try it out and let us know what you think.
