### ISSUE TITLE
Latest version for unreal engine

### ISSUE THREAD

**Issue by avivazran** [ValveSoftware/steam-audio#125]
Unreal engine plugin is 0.17 version. 
Will 0.18 be released to unreal engine soon?

**Comment by 1runeberg** [comment]
Hi Aviv - the plugin is in version 2.0 release. .17 refers to beta 17 of Steam Audio. Or are you looking for some specific feature in beta 18 of Steam Audio thats not in Unreal at the moment?

**Comment by avivazran** [comment]
Yes exactly. Unreal engine plugin is currently the beta 17 while the beta 18 seems to provide much needed functionality for my academic research. 
When will the unreal plugin gets updated to the latest beta?

**Comment by avivazran** [comment]
I need the ability to control each sound source occlusion samples and custom attenuation curves feature. 
I’ve searched the web but there There isn’t any updated unreal plugin

**Comment by 1runeberg** [comment]
Hi @avivazran - Thanks for the feedback, beta 18 is fairly new but its is available in our Unity implementation. For Unreal, will post any relevant news/updates in this GitHub issue when we have something more concrete to share.

Please note though, that release cadence for Steam Audio in Unreal is tightly tied with the UE4 major version release cadence as an SDK update (e.g. beta 17 to beta 18) will also need to be properly QA'd both from our end and Epic's and this can take a while so I wouldn't rely on this for any current or immediate projects you might have.

**Comment by SkacikPL** [comment]
On one side this seems like major necro revive of existing issue thread and on another one - it's kinda necessary because nothing has changed on the front.

Is UE4 support cancelled or has it fallen just _that_ low in priority list, both UE4 and Steam Audio had several major releases since last post in this thread but UE4 version of the plugin hasn't been updated since 2.0 beta 17 (so over two years by now)

This is kinda sad, i was considering building an UE4 project around use of Steam Audio but existing beta 17 is far from reliably usable and absolute lack of updates also doesn't look very promising.

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.
