### ISSUE TITLE
[Unity] Strange behavior when using Physics Based Attention For Indirect when Physics Based Attention is disabled. 2.0.19beta

### ISSUE THREAD

**Issue by DenisSulyagin** [ValveSoftware/steam-audio#146]
Strange behavior and error when using "Physics Based Attention For Indirect" when "Physics Based Attention" is disabled. The distance to the listener begins to increase, then ends with an crash.

**Comment by lakulish** [comment]
Can you provide some more details about how you have configured your scene? Ideally, if you could provide us with a minimal scene in which the problem occurs, that would be best. Otherwise, let us know what your scene looks like, what your Steam Audio Source settings look like, and what the settings on the Steam Audio tab look like. Thanks!
