### ISSUE TITLE
Wrong coordinate system type in documentation

### ISSUE THREAD

**Issue by davidebeatrici** [ValveSoftware/steam-audio#15]
From _IPLVector3_'s detailed description:

`Phonon uses a right-handed coordinate system, with the x-axis pointing right, the y-axis pointing up, and the z-axis pointing ahead. Position and direction data obtained from a game engine or audio engine must be properly transformed before being passed to any Phonon API function.`

I think that it's wrong, because it's the left-handed coordinate system that has the z-axis pointing ahead.
The right-handed coordinate system's z-axis is pointing backward.

**Comment by lakulish** [comment]
Good catch. That should have read "the _positive_ x-axis pointing right, the _positive_ y-axis pointing up, and the _negative_ z-axis pointing ahead". We will update the documentation accordingly.

**Comment by davidebeatrici** [comment]
Thank you for your answer.
Are there any specific reasons for choosing the right-handed coordinate system over the left-handed one?I'm asking this because the majority of game engines uses the left-handed type.

**Comment by lakulish** [comment]
We have just released Steam Audio v2.0-beta.2. The documentation should be updated appropriately.

Get the latest version from https://valvesoftware.github.io/steam-audio/.

As for why we chose a right-handed coordinate system, this was an arbitrary choice made a long time ago. Among other things, OpenGL uses a right-handed coordinate system, so that was perhaps a factor in the decision.

**Comment by davidebeatrici** [comment]
The documentation is now correct about the used coordinate system.

Thank you for your help.
