### ISSUE TITLE
[UE 5.3.2]Dynamic objects issues

### ISSUE THREAD

**Issue by SkacikPL** [ValveSoftware/steam-audio#322]
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.5.2
- (If applicable) Unity version: N/A
- (If applicable) Unreal Engine version: 5.3.2
- (If applicable) FMOD Studio version: N/a
- Operating System and version: W11x64
- (Optional) CPU architecture (e.g. x86-64, armv7): x86-64

**Issue Description**
When using raytracers other than default, dynamic objects cause different issues.
With Embree the project will crash nearly instantly upon instancing the scene with dynamic objects.
With RadeonRays(if enabled by applying https://github.com/ValveSoftware/steam-audio/issues/289) the project will not crash but dynamic objects are not processed at all - they do not occlude sounds nor bounce any reverbs, etc.

**Also - i'm almost entirely certain that export function for dynamic objects does not properly support meshes whose origin isn't in the center of the mesh, making something like a door with origin on the "hinge" will cause rotational mismatch.**

**Steps To Reproduce**
1.Create a project
2.Create a scene with dynamic objects
3.Set Raytracer to either Embree or RadeonRays
4.With embree project will crash whilst RR will not process any occlusion/reverbs for dynamic objects

**Comment by lakulish** [comment]
@SkacikPL We're able to reproduce this issue. When the scene type is set to Embree, the issue is caused by unexpected behavior within Embree, which we were able to trace to an issue with the build settings for Embree. A fix will be available shortly.

Note that Steam Audio does not currently support instanced meshes when the scene type is set to Radeon Rays.
