### ISSUE TITLE
Can SteamAudio plugin be used on visionOS?

### ISSUE THREAD

**Issue by CodeNewWorlds** [ValveSoftware/steam-audio#348]

**Comment by lakulish** [comment]
Since Steam Audio is now open source, you can modify it to be built on many more platforms than the officially supported ones. The following recent commit (https://github.com/ValveSoftware/steam-audio/commit/1bc528f4712840b1174c86c4f1fdcfdce28db66e) should allow Steam Audio to be built for visionOS, although we have not tested this.

**Comment by CodeNewWorlds** [comment]
Hi, follow the commit [https://github.com/ValveSoftware/steam-audio/commit/1bc528f4712840b1174c86c4f1fdcfdce28db66e](url), I can built succeed, but only libaudioplugin_phonon.a generated and I can't generate libphonon.a.
I have two questions that what's the difference between libaudioplugin_phonon.a and libphonon.a and how can i generate  libphonon.a?
