### ISSUE TITLE
Support to route AudioMixer channel(s) to multiple spatial 'speakers'

### ISSUE THREAD

**Issue by davidhaley** [ValveSoftware/steam-audio#52]
Good evening,

I am building a VR DJ application. Multiple AudioSources, representing turntables, are mixed together using Unity's AudioMixer, and are then sent out of the AudioMixer's master channel. I would like to route the AudioMixer's master channel to multiple 'speakers', each with an effect on them ( LPF for subs and HPF for PA's ). If possible, I do not want to use multiple AudioSources to achieve the effect of additional speakers ( my current implementation ), because updating every individual AudioSource.timesamples is slow. I would like to use only the PCM Data from the Audio Thread from a single audio source, for many speakers. I would like to keep high-quality real-time spatial audio. Is this currently possible?

Thank you!

**Comment by lakulish** [comment]
@davidhaley Just so that I understand this correctly, can you confirm if the following is what you're trying to achieve?

1. An Audio Mixer emits multi-channel output.
2. A separate effect is applied to each channel of the output.
3. Each channel of this output is spatialized separately, from a different position, and the spatialized results are mixed.
4. The mixed, spatialized output is sent to the master output (the speakers, essentially).

Correct me if I've misunderstood something here. A couple of questions:

* What kind of effects do you want to apply in step 2? Something from Steam Audio? Or just general effects like low-pass filters?
* Do you need control over the 3D positions from which each channel is spatialized in step 3?

Generally speaking, this functionality is not currently available out of the box in the Steam Audio plugin for Unity. At this time, you will probably need to write a Unity mixer plugin in C++, that does this for you, particularly step 2. For step 3, you can use the Virtual Surround Effect in the Steam Audio API from within your mixer plugin, or multiple Object-Based Binaural Effects if you need control over the 3D positions of each channel.

Do let me know if you had something else in mind.
