### ISSUE TITLE
`Vector3' is an ambiguous reference between `UnityEngine.Vector3' and `SteamAudio.Vector3'

### ISSUE THREAD

**Issue by CraigASanford** [ValveSoftware/steam-audio#71]
When adding the "Using SteamAudio" in C# scripts I get the below error.

error CS0104: `Vector3' is an ambiguous reference between `UnityEngine.Vector3' and `SteamAudio.Vector3'

I realize I can get around this via not using the namespace and directly typing out SteamAudio.Vector3. Just thought you may want to be aware of this as a class name change may be easier on users so the namespace can be used.

**Comment by lakulish** [comment]
We use `SteamAudio.Vector3` because the underlying type in the Steam Audio C API is called `IPLVector3`. The correct way to resolve this ambiguity is to explicitly say `UnityEngine.Vector3` or `SteamAudio.Vector3` as needed. A beneficial side-effect of this is that your code will automatically be explicit about which coordinate system you're expressing your vectors in.
