### ISSUE TITLE
C API: iplApplyDirectSoundEffect propagation delay

### ISSUE THREAD

**Issue by jampekka** [ValveSoftware/steam-audio#79]
`iplGetDirectSoundPath` computes the propagation delay, but applying the path effects to data using `iplApplyDirectSoundEffect` does not seem to apply this to the signal. For example a sound source 100m away correctly gives a delay of approximately 0.3 seconds, but in the resulting signal the sound starts instantly. Judging by the waveform the attenuation effects are correctly applied.

Is there a way to delay the signal in Steam Audio, or is this designed to be handled by client code?

**Comment by achandak** [comment]
Delay is something you will have to apply on your own. For both the direct sound and all the reflected sound, the filter (IR) is shifted by the delay for the direct path. So, the overall response is correct minus the delay. 

The choice was made because most often a sound source is moving and introducing delay for the direct path also introduces Doppler which may not be a desirable effect always. In addition, this is something a user can always apply to the final processed signal.

**Comment by aluo-x** [comment]
@achandak @jampekka Could you confirm that this is still the case? 
I saw [this post](https://steamcommunity.com/app/596420/discussions/0/2293968408151013056/) on the steam forums, but the wording is pretty confusing. 

My understanding from your post and the post on the forums, is that there is no true distance based delay for either direct or reflected sounds, and that any delay would come from the HRTF (measured at 1m?). 

So suppose I have a wall, a listener, and an impulse generated, all on a line, the reflection & the direct sound would reach me at the same time?
