### ISSUE TITLE
Unity3D, Very high GC memory allocation 32kb/frame when using unity RayCast 

### ISSUE THREAD

**Issue by friuns2** [ValveSoftware/steam-audio#84]
Hi. There is high memory allocation, when using "unity RayCast" mode and Occlusion method set to Partial in Steam audio source.

![Image of Yaktocat](https://i.imgur.com/ewfS2YL.png)

I think it happens because of passing delegate to native dll.

**Comment by lakulish** [comment]
The Unity ray tracer's `Physics.Raycast` function results in GC allocation every time rays are traced. Starting with Unity 2017.1, you can use the function `Physics.RaycastNonAlloc` to trace rays without causing any GC allocation. If you are using Unity 2017.1 or later, you can try modifying the file Assets/SteamAudio/RayTracer.cs and replacing all calls to `Physics.Raycast` with calls to `Physics.RaycastNonAlloc`. Let us know if this helps resolve the issue.

**Comment by friuns2** [comment]
didn't help i even commented out Physics.Raycast all together returning false. 
i think its because when SteamAudio engine calls AnyHit it creates those arrays float[] rayOrigin, float[] rayDirection, to avoid GC you could use structs or just passing x,y,z floats directly
```cs
  public static void AnyHit(float[] rayOrigin,
                                  float[] rayDirection,
                                  float minDistance,
                                  float maxDistance,
                                  ref int hitExists,
                                  IntPtr userData)
```
i uploaded demo scene, https://drive.google.com/file/d/1sda9FFsX6WJekeQYyw8hiuBlA6lB-obd/view?usp=drivesdk

Steps i did  to reproduce
1. Add SteamAudioListener, SteamAudioCustomSettings, Change RayTrace to unity
2. Add AudioSource with SteamAudioSource audio, enable Direct Sound Occluson, and set Occlusion Method to partial with radius 10
3. Run and open profiler

**Comment by lakulish** [comment]
So I was able to repro the issue, and it turns out there are three places where GC allocations happen:

1. Physics.Raycast. This can be fixed by switching to Physics.RaycastNonAlloc, as I mentioned previously.
2. .NET marshaling of the `float[] rayOrigin` and `float[] rayDirection` parameters to `AnyHit`, as you mentioned. Unfortunately, this can't be replaced with structs or raw xyz values because the signature must match the C API callback. Instead, the workaround is to accept these parameters as `IntPtr` instead, and get their values without allocating anything by using `Marshal.Copy` to copy into a pre-allocated buffer.
3. Querying the current scene's `LayerMask` involves a call to `GameObject.FindObjectOfType`. This can be worked around by caching the value until the scene changes.

These three workarounds have been implemented and it looks like there are no more GC allocations in `AnyHit`. These changes will be part of the next release of Steam Audio.

Meanwhile, I'm attaching the changed files so you can drop them into your project as a temporary measure if needed. Place these in Assets/SteamAudio in your Unity project.

[SteamAudio.zip](https://github.com/ValveSoftware/steam-audio/files/3014692/SteamAudio.zip)

Let me know if this resolves the issue, or if you are still seeing GC allocations.

**Comment by friuns2** [comment]
Thanks it works! no GC allocations anymore.

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue.
